// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Yelp;
//
//    var yelpRating = YelpRating.FromJson(jsonString);

namespace Yelp
{
    using Newtonsoft.Json;

    public partial class BusinessWithReview : Business
    {
        private ReviewNamespace.Review[] reviews;
        private long total;
        private string[] possibleLanguages;

        [JsonProperty("reviews")]
        public ReviewNamespace.Review[] Reviews { get => reviews; set => reviews = value; }

        [JsonProperty("total")]
        public long Total { get => total; set => total = value; }

        [JsonProperty("possible_languages")]
        public string[] PossibleLanguages { get => possibleLanguages; set => possibleLanguages = value; }
    }

    public partial class BusinessWithReview
    {
        public static BusinessWithReview FromJson(string json) => JsonConvert.DeserializeObject<BusinessWithReview>(json, Yelp.Converter.Settings);
    }

    public static class Serialize2
    {
        public static string ToJson(this BusinessWithReview self) => JsonConvert.SerializeObject(self, Yelp.Converter.Settings);
    }
}
