// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BreweryNamespace;
//
//    var brewery = Brewery.FromJson(jsonString);

namespace BreweryNamespace
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Brewery
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("brewery_type")]
        public BreweryType BreweryType { get; set; }

        [JsonProperty("street")]
        public string Street { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public State State { get; set; }

        [JsonProperty("postal_code")]
        public string PostalCode { get; set; }

        [JsonProperty("country")]
        public Country Country { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("website_url")]
        public string WebsiteUrl { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("tag_list")]
        public object[] TagList { get; set; }
    }

    public enum BreweryType { Brewpub, Contract, Micro, Planning, Regional };

    public enum Country { UnitedStates };

    public enum State { Alabama, Alaska, Arizona, Arkansas, Ohio };

    public partial class Brewery
    {
        public static Brewery[] FromJson(string json) => JsonConvert.DeserializeObject<Brewery[]>(json, BreweryNamespace.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Brewery[] self) => JsonConvert.SerializeObject(self, BreweryNamespace.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                BreweryTypeConverter.Singleton,
                CountryConverter.Singleton,
                StateConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class BreweryTypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(BreweryType) || t == typeof(BreweryType?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "brewpub":
                    return BreweryType.Brewpub;
                case "contract":
                    return BreweryType.Contract;
                case "micro":
                    return BreweryType.Micro;
                case "regional":
                    return BreweryType.Regional;
                case "planning":
                    return BreweryType.Planning;
            }
            throw new Exception("Cannot unmarshal type BreweryType");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (BreweryType)untypedValue;
            switch (value)
            {
                case BreweryType.Brewpub:
                    serializer.Serialize(writer, "brewpub");
                    return;
                case BreweryType.Contract:
                    serializer.Serialize(writer, "contract");
                    return;
                case BreweryType.Micro:
                    serializer.Serialize(writer, "micro");
                    return;
                case BreweryType.Regional:
                    serializer.Serialize(writer, "regional");
                    return;
                case BreweryType.Planning:
                    serializer.Serialize(writer, "planning");
                    return;
            }
            throw new Exception("Cannot marshal type BreweryType");
        }

        public static readonly BreweryTypeConverter Singleton = new BreweryTypeConverter();
    }

    internal class CountryConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Country) || t == typeof(Country?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "United States")
            {
                return Country.UnitedStates;
            }
            throw new Exception("Cannot unmarshal type Country");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Country)untypedValue;
            if (value == Country.UnitedStates)
            {
                serializer.Serialize(writer, "United States");
                return;
            }
            throw new Exception("Cannot marshal type Country");
        }

        public static readonly CountryConverter Singleton = new CountryConverter();
    }

    internal class StateConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(State) || t == typeof(State?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Alabama":
                    return State.Alabama;
                case "Alaska":
                    return State.Alaska;
                case "Arizona":
                    return State.Arizona;
                case "Arkansas":
                    return State.Arkansas;
                case "Ohio":
                    return State.Ohio;
            }
            throw new Exception("Cannot unmarshal type State");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (State)untypedValue;
            switch (value)
            {
                case State.Alabama:
                    serializer.Serialize(writer, "Alabama");
                    return;
                case State.Alaska:
                    serializer.Serialize(writer, "Alaska");
                    return;
                case State.Arizona:
                    serializer.Serialize(writer, "Arizona");
                    return;
                case State.Arkansas:
                    serializer.Serialize(writer, "Arkansas");
                    return;
                case State.Ohio:
                    serializer.Serialize(writer, "Ohio");
                    return;
            }
            throw new Exception("Cannot marshal type State");
        }

        public static readonly StateConverter Singleton = new StateConverter();
    }
}
