// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BusinessNamespace;
//
//    var businessWithRating = BusinessWithRating.FromJson(jsonString);

namespace BusinessNamespace
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BusinessWithRating
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("breweryType")]
        public BreweryType BreweryType { get; set; }

        [JsonProperty("street")]
        public string Street { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public long State { get; set; }

        [JsonProperty("postalCode")]
        public string PostalCode { get; set; }

        [JsonProperty("country")]
        public long Country { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("websiteUrl")]
        public Uri WebsiteUrl { get; set; }

        [JsonProperty("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("tagList")]
        public string[] TagList { get; set; }

        [JsonProperty("rating")]
        public double Rating { get; set; }

    }
    public enum BreweryType { Brewpub, Contract, Micro, Planning, Regional };

    public partial class BusinessWithRating
    {
        public static BusinessWithRating[] FromJson(string json) => JsonConvert.DeserializeObject<BusinessWithRating[]>(json, BusinessNamespace.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this BusinessWithRating[] self) => JsonConvert.SerializeObject(self, BusinessNamespace.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }


    internal class BreweryTypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(BreweryType) || t == typeof(BreweryType?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "brewpub":
                    return BreweryType.Brewpub;
                case "contract":
                    return BreweryType.Contract;
                case "micro":
                    return BreweryType.Micro;
                case "regional":
                    return BreweryType.Regional;
                case "planning":
                    return BreweryType.Planning;
            }
            throw new Exception("Cannot unmarshal type BreweryType");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (BreweryType)untypedValue;
            switch (value)
            {
                case BreweryType.Brewpub:
                    serializer.Serialize(writer, "brewpub");
                    return;
                case BreweryType.Contract:
                    serializer.Serialize(writer, "contract");
                    return;
                case BreweryType.Micro:
                    serializer.Serialize(writer, "micro");
                    return;
                case BreweryType.Regional:
                    serializer.Serialize(writer, "regional");
                    return;
                case BreweryType.Planning:
                    serializer.Serialize(writer, "planning");
                    return;
            }
            throw new Exception("Cannot marshal type BreweryType");
        }

        public static readonly BreweryTypeConverter Singleton = new BreweryTypeConverter();
    }

}